### ISSUE TITLE
search.cfg

### ISSUE THREAD

**Issue by cxc61cxc** [zsiki/configurable_search#1]
Hi,
thanks for the work done on the plugin.
I don't quite understand what are the parameters to be entered and how. Can the research also be applied to layers on postgis?
please provide some sample for configuration files
thank you
ciao
Carlo

**Comment by zsiki** [comment]
I've never tried with postgis layer. That case base directory should be empty. I'll test it.

**Comment by zsiki** [comment]
At the moment the plug.in cannot be used for PostGIS layer, neither for Geopackage and SpatiaLite layers. Only the file based layers (for example shape, tab) are supported. I'll work in the near future to support layers stored in the database.
Thanks for your feed back.

**Comment by zsiki** [comment]
The new version (0.2) of the plugin is available from the repo at  plugins.qgis.org. Any layer can be used by layer name, file based layers (.e.g. shape file, mapinfo tab, etc.) can be used both by name and full path). Be careful the layer name can be the same for more layers in qgis, that case giving the layer name in the configuration is ambiguous.
Feedback is welcome.
